In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

from sklearn.preprocessing import LabelEncoder

In [4]:
titanic = pd.read_csv('statisticalDf.csv')
titanic

         ClassName      mean       RMS    median        sd
0   alibadawixStra  0.033099  3.073613  0.003644  3.073540
1   dinaelgendyxSt  0.289030  2.611417  0.022012  2.595477
2   farahxStraight  0.080009  2.349435  0.057967  2.348142
3   ghazalyStraigh -0.151838  3.329079 -0.025638  3.325722
4   habibatarabayS  0.035061  1.610551  0.020208  1.610215
5   hananabilxStra  0.023485  1.822683  0.060164  1.822585
6   hashemdakroury  0.080534  3.691773  0.153445  3.691022
7   heidiStraightW  0.205574  2.724726  0.186817  2.717069
8   hoshantStraigh -0.249517  4.236537 -0.153113  4.229327
9   ismail2Straigh  0.241531  3.349942  0.114469  3.341345
10  janahStraightW  0.101679  1.393076  0.153439  1.389411
11  janqhStraightW  0.037997  2.039216  0.058797  2.038936
12  KarenxStraight  0.129995  2.159648  0.078643  2.155788
13  mayarahmedxStr  0.137606  1.863985  0.104521  1.858951
14  miraalmouayadS  0.190740  1.887748  0.140712  1.878151
15  moatazStraight -0.089947  1.874230 -0.084018  1.872140
16  MohamedDawodSt  0.230543  2.058516  0.108043  2.045628
17  mohamedelshour -0.038164  4.122967  0.262700  4.122922
18  moustafahabybe  0.179787  2.732009  0.082520  2.726170
19  nourhanStraigh -0.029009  1.722411 -0.156584  1.722222
20  olabasemStraig -0.013459  2.875187  0.142124  2.875248
21  rollabasemStra  0.183740  1.480535  0.002128  1.469134
22  salwaStraightW  0.162935  2.286583  0.168288  2.280859
23  seifanaStraigh -0.383819  3.601661 -0.148406  3.581270
24  seifzakariaxSt  0.123001  5.066327  0.074946  5.065016
25  tokhye2Straigh  0.127716  4.052343  0.277373  4.050481
26  waedhatemxStra -0.116186  2.052855  0.056959  2.049625
27  yaseenriadStra  0.051579  3.538680  0.076351  3.538423
28  youssefemad2xS -0.115953  2.785611 -0.029872  2.783296
29  youssefStraigh -0.473660  4.355108 -0.169371  4.329441
30  YusufStraightW  0.366996  3.185013  0.272204  3.163891
31  zoz5xStraightW  0.024825  1.941531  0.048966  1.941433

In [7]:
label_column = 'ClassName'
label_encoder = LabelEncoder()
titanic[label_column] = label_encoder.fit_transform(titanic[label_column])

In [8]:
titanic

    ClassName      mean       RMS    median        sd
0           3  0.033099  3.073613  0.003644  3.073540
1           4  0.289030  2.611417  0.022012  2.595477
2           5  0.080009  2.349435  0.057967  2.348142
3           6 -0.151838  3.329079 -0.025638  3.325722
4           7  0.035061  1.610551  0.020208  1.610215
5           8  0.023485  1.822683  0.060164  1.822585
6           9  0.080534  3.691773  0.153445  3.691022
7          10  0.205574  2.724726  0.186817  2.717069
8          11 -0.249517  4.236537 -0.153113  4.229327
9          12  0.241531  3.349942  0.114469  3.341345
10         13  0.101679  1.393076  0.153439  1.389411
11         14  0.037997  2.039216  0.058797  2.038936
12          0  0.129995  2.159648  0.078643  2.155788
13         15  0.137606  1.863985  0.104521  1.858951
14         16  0.190740  1.887748  0.140712  1.878151
15         17 -0.089947  1.874230 -0.084018  1.872140
16          1  0.230543  2.058516  0.108043  2.045628
17         18 -0.038164  4.122967  0.262700  4.122922
18         19  0.179787  2.732009  0.082520  2.726170
19         20 -0.029009  1.722411 -0.156584  1.722222
20         21 -0.013459  2.875187  0.142124  2.875248
21         22  0.183740  1.480535  0.002128  1.469134
22         23  0.162935  2.286583  0.168288  2.280859
23         24 -0.383819  3.601661 -0.148406  3.581270
24         25  0.123001  5.066327  0.074946  5.065016
25         26  0.127716  4.052343  0.277373  4.050481
26         27 -0.116186  2.052855  0.056959  2.049625
27         28  0.051579  3.538680  0.076351  3.538423
28         30 -0.115953  2.785611 -0.029872  2.783296
29         29 -0.473660  4.355108 -0.169371  4.329441
30          2  0.366996  3.185013  0.272204  3.163891
31         31  0.024825  1.941531  0.048966  1.941433

In [9]:

dataset = titanic.copy()
X = np.asarray(dataset.drop('ClassName', 1))
y = np.asarray(dataset['ClassName'])
y[y==0] = -1

C:\Users\szizo\AppData\Local\Temp\ipykernel_9920\3125231882.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = np.asarray(dataset.drop('ClassName', 1))

In [10]:
X.shape

(32, 4)

In [11]:
y[0:20]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, -1, 15, 16, 17,  1,
       18, 19, 20])

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [13]:
X_train.shape

(25, 4)

In [14]:
print(X_test.shape,y_test.shape)

(7, 4) (7,)

In [15]:
sc = StandardScaler()
X_train_normalized = sc.fit_transform(X_train)
X_test_normalized = sc.transform(X_test)

In [16]:

svmModel = SVC(kernel = 'rbf',C=2,gamma = 0.9)
svmModel.fit(X_train_normalized,y_train)
Y_pred = svmModel.predict(X_test_normalized)
print(round(accuracy_score(y_test, Y_pred)*100,2))

0.0