In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
import seaborn as sns # for plotting.
import os
import math

from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.DataFrame(columns=['name','mean_LA(x)', 'mean_LA(y)', 'mean_LA(z)', 'mean_GY(x)', 'mean_GY(y)', 'mean_GY(z)','sd_LA(x)', 'sd_LA(y)', 'sd_LA(z)', 'sd_GY(x)', 'sd_GY(y)', 'sd_GY(z)'])

In [3]:
directory = os.path.join(os.getcwd(), 'hand\\training')
x=1
firstTime = True
for filename in os.listdir(directory):
    if (filename.endswith(".csv")):
        filepath = os.path.join(directory, filename)
        try:
            testOriginal = pd.read_csv(filepath)
            test=testOriginal.copy()
            num_rows_before = test.shape[0]

            fivePercent = num_rows_before * 0.2
            fivePercent = math.ceil(fivePercent)

            #test = test.iloc[fivePercent:]
            
            
            test = test.iloc[:-fivePercent]

            num_rows = test.shape[0]
            # Create a new row of data
            new_row = [filename,test['LA(x)'].mean(),test['LA(y)'].mean(),test['LA(z)'].mean(),test['GY(x)'].mean(),test['GY(y)'].mean(),test['GY(z)'].mean(),test['LA(x)'].std(),test['LA(y)'].std(),test['LA(z)'].std(),test['GY(x)'].std(),test['GY(y)'].std(),test['GY(z)'].std()]

            # Add the new row to the DataFrame
            df.loc[len(df)] = new_row
        except Exception as e:
            print(f"Error occurred while reading file: {filename}")
            print(f"Error message: {str(e)}")
            continue

In [4]:
df

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,ahmedamir.csv,0.900060,-0.965049,0.714376,-0.013971,-0.155567,0.041762,3.824209,2.992793,2.644413,1.009395,1.214170,1.437600
1,ghazaly.csv,0.026040,-0.404830,0.129242,0.029543,0.155535,0.478177,0.841483,1.140295,1.569531,0.241602,0.400055,0.934533
2,habibatarabay.csv,0.392152,-0.462110,0.553301,-0.166631,0.020810,-0.001487,2.439593,2.094473,1.671452,1.035005,0.848799,1.010451
3,hashem.csv,0.002777,-0.261593,0.043542,-0.367994,0.233681,-0.089440,1.610852,1.505165,0.867599,0.658520,0.445233,0.451626
4,heidi.csv,-0.730693,-0.757379,0.506630,0.177046,-0.165480,0.604981,1.822200,2.397183,2.496371,1.028706,0.747703,1.236120
5,hussenhany.csv,-0.006258,-0.526168,0.327254,0.105078,0.221316,0.469326,1.275037,1.564392,2.906907,0.373177,0.574268,0.965862
6,ismail.csv,0.092198,-0.434006,0.262996,0.013348,0.089219,0.157710,1.059901,1.047598,1.543881,0.340469,0.529773,0.892956
7,judy.csv,0.330886,-0.183648,0.263214,0.021105,-0.067694,-0.170577,1.089285,0.966052,1.721033,0.400270,0.542752,0.824878
8,mira.csv,0.712194,-1.816702,0.990533,0.443608,-0.429236,-0.069807,4.284499,3.310251,2.383009,0.926856,0.977162,1.828933
9,mohamed.csv,0.269306,-0.448650,0.164584,-0.014954,-0.021956,-0.107034,1.060842,1.026368,1.688733,0.487122,0.455121,0.946564
10,mohameddawoud.csv,0.168411,-0.370416,0.168652,0.028707,0.049733,0.155097,0.803503,0.913108,1.242390,0.235900,0.375851,0.912622
11,mohamedelshoura.csv,-0.673774,-0.951370,-0.417185,-0.478144,-0.128280,0.037818,2.549466,3.178923,1.639955,0.933311,0.490194,1.337298
12,moustafa.csv,0.053496,-0.261486,0.151948,0.054137,0.186128,0.340907,0.742779,0.821428,1.228647,0.267397,0.314201,0.482874

In [5]:
directory = os.path.join(os.getcwd(), 'hand\\testing')
x=1
firstTime = True
for filename in os.listdir(directory):
    if (filename.endswith(".csv")):
        filepath = os.path.join(directory, filename)
        try:
            testOriginal = pd.read_csv(filepath)
            test=testOriginal.copy()

            num_rows_before = test.shape[0]

            fivePercent = num_rows_before * 0.2
            fivePercent = math.ceil(fivePercent)

            #test = test.iloc[fivePercent:]
            #test = test.iloc[:-fivePercent]


            num_rows = test.shape[0]
            start_row = 0
            end_row = num_rows/2
            end_row = math.ceil(end_row)
            print(end_row)   
            # Create a new row of data
            new_row = [filename,test['LA(x)'][start_row:end_row].mean(),test['LA(y)'][start_row:end_row].mean(),test['LA(z)'][start_row:end_row].mean(),test['GY(x)'][start_row:end_row].mean(),test['GY(y)'][start_row:end_row].mean(),test['GY(z)'][start_row:end_row].mean(),test['LA(x)'][start_row:end_row].std(),test['LA(y)'][start_row:end_row].std(),test['LA(z)'][start_row:end_row].std(),test['GY(x)'][start_row:end_row].std(),test['GY(y)'][start_row:end_row].std(),test['GY(z)'][start_row:end_row].std()]

            # Add the new row to the DataFrame
            df.loc[len(df)] = new_row
        except Exception as e:
            print(f"Error occurred while reading file: {filename}")
            print(f"Error message: {str(e)}")
            continue

7518
7254
7102
6647
5732
6017
7349

In [6]:
df

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,ahmedamir.csv,0.900060,-0.965049,0.714376,-0.013971,-0.155567,0.041762,3.824209,2.992793,2.644413,1.009395,1.214170,1.437600
1,ghazaly.csv,0.026040,-0.404830,0.129242,0.029543,0.155535,0.478177,0.841483,1.140295,1.569531,0.241602,0.400055,0.934533
2,habibatarabay.csv,0.392152,-0.462110,0.553301,-0.166631,0.020810,-0.001487,2.439593,2.094473,1.671452,1.035005,0.848799,1.010451
3,hashem.csv,0.002777,-0.261593,0.043542,-0.367994,0.233681,-0.089440,1.610852,1.505165,0.867599,0.658520,0.445233,0.451626
4,heidi.csv,-0.730693,-0.757379,0.506630,0.177046,-0.165480,0.604981,1.822200,2.397183,2.496371,1.028706,0.747703,1.236120
5,hussenhany.csv,-0.006258,-0.526168,0.327254,0.105078,0.221316,0.469326,1.275037,1.564392,2.906907,0.373177,0.574268,0.965862
6,ismail.csv,0.092198,-0.434006,0.262996,0.013348,0.089219,0.157710,1.059901,1.047598,1.543881,0.340469,0.529773,0.892956
7,judy.csv,0.330886,-0.183648,0.263214,0.021105,-0.067694,-0.170577,1.089285,0.966052,1.721033,0.400270,0.542752,0.824878
8,mira.csv,0.712194,-1.816702,0.990533,0.443608,-0.429236,-0.069807,4.284499,3.310251,2.383009,0.926856,0.977162,1.828933
9,mohamed.csv,0.269306,-0.448650,0.164584,-0.014954,-0.021956,-0.107034,1.060842,1.026368,1.688733,0.487122,0.455121,0.946564
10,mohameddawoud.csv,0.168411,-0.370416,0.168652,0.028707,0.049733,0.155097,0.803503,0.913108,1.242390,0.235900,0.375851,0.912622
11,mohamedelshoura.csv,-0.673774,-0.951370,-0.417185,-0.478144,-0.128280,0.037818,2.549466,3.178923,1.639955,0.933311,0.490194,1.337298
12,moustafa.csv,0.053496,-0.261486,0.151948,0.054137,0.186128,0.340907,0.742779,0.821428,1.228647,0.267397,0.314201,0.482874
13,ola.csv,0.108910,-0.407179,0.662535,-0.020668,-0.032709,0.024278,1.683670,2.272056,1.581942,1.475667,0.399223,0.586404
14,rolla.csv,0.216866,-0.528242,-0.049357,-0.001227,0.028715,-0.003257,1.217630,1.487113,1.943382,0.485284,0.321013,1.131530
15,salwa.csv,0.211745,-0.727425,-0.076628,0.038244,-0.135960,0.468363,1.756172,1.651001,2.957945,0.954857,0.571199,1.080063
16,seifana.csv,-0.150600,-0.546184,0.296190,0.104065,0.177521,0.474079,1.288246,1.284170,2.314333,0.465309,0.479223,0.928446
17,tokhye.csv,-0.039692,-0.316662,0.065548,0.089553,0.019198,0.403736,1.413875,1.223536,2.908938,0.579944,0.402881,0.858414
18,youssef.csv,0.237372,-0.918822,1.106458,0.443280,-0.247797,0.058343,3.270762,3.094006,1.887799,1.316618,0.880323,1.120145
19,yusuf.csv,-0.062385,-0.446527,0.204720,0.011673,0.253974,0.461554,0.772383,0.671823,1.171294,0.192333,0.402633,0.646103

In [7]:
label_column = 'name'
label_encoder = LabelEncoder()
df[label_column] = label_encoder.fit_transform(df[label_column])

In [8]:
df

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,0,0.900060,-0.965049,0.714376,-0.013971,-0.155567,0.041762,3.824209,2.992793,2.644413,1.009395,1.214170,1.437600
1,1,0.026040,-0.404830,0.129242,0.029543,0.155535,0.478177,0.841483,1.140295,1.569531,0.241602,0.400055,0.934533
2,2,0.392152,-0.462110,0.553301,-0.166631,0.020810,-0.001487,2.439593,2.094473,1.671452,1.035005,0.848799,1.010451
3,3,0.002777,-0.261593,0.043542,-0.367994,0.233681,-0.089440,1.610852,1.505165,0.867599,0.658520,0.445233,0.451626
4,4,-0.730693,-0.757379,0.506630,0.177046,-0.165480,0.604981,1.822200,2.397183,2.496371,1.028706,0.747703,1.236120
5,5,-0.006258,-0.526168,0.327254,0.105078,0.221316,0.469326,1.275037,1.564392,2.906907,0.373177,0.574268,0.965862
6,6,0.092198,-0.434006,0.262996,0.013348,0.089219,0.157710,1.059901,1.047598,1.543881,0.340469,0.529773,0.892956
7,7,0.330886,-0.183648,0.263214,0.021105,-0.067694,-0.170577,1.089285,0.966052,1.721033,0.400270,0.542752,0.824878
8,8,0.712194,-1.816702,0.990533,0.443608,-0.429236,-0.069807,4.284499,3.310251,2.383009,0.926856,0.977162,1.828933
9,9,0.269306,-0.448650,0.164584,-0.014954,-0.021956,-0.107034,1.060842,1.026368,1.688733,0.487122,0.455121,0.946564
10,10,0.168411,-0.370416,0.168652,0.028707,0.049733,0.155097,0.803503,0.913108,1.242390,0.235900,0.375851,0.912622
11,11,-0.673774,-0.951370,-0.417185,-0.478144,-0.128280,0.037818,2.549466,3.178923,1.639955,0.933311,0.490194,1.337298
12,12,0.053496,-0.261486,0.151948,0.054137,0.186128,0.340907,0.742779,0.821428,1.228647,0.267397,0.314201,0.482874
13,13,0.108910,-0.407179,0.662535,-0.020668,-0.032709,0.024278,1.683670,2.272056,1.581942,1.475667,0.399223,0.586404
14,14,0.216866,-0.528242,-0.049357,-0.001227,0.028715,-0.003257,1.217630,1.487113,1.943382,0.485284,0.321013,1.131530
15,15,0.211745,-0.727425,-0.076628,0.038244,-0.135960,0.468363,1.756172,1.651001,2.957945,0.954857,0.571199,1.080063
16,16,-0.150600,-0.546184,0.296190,0.104065,0.177521,0.474079,1.288246,1.284170,2.314333,0.465309,0.479223,0.928446
17,17,-0.039692,-0.316662,0.065548,0.089553,0.019198,0.403736,1.413875,1.223536,2.908938,0.579944,0.402881,0.858414
18,18,0.237372,-0.918822,1.106458,0.443280,-0.247797,0.058343,3.270762,3.094006,1.887799,1.316618,0.880323,1.120145
19,19,-0.062385,-0.446527,0.204720,0.011673,0.253974,0.461554,0.772383,0.671823,1.171294,0.192333,0.402633,0.646103

In [9]:
df_testingHalf = pd.DataFrame(columns=['name','mean_LA(x)', 'mean_LA(y)', 'mean_LA(z)', 'mean_GY(x)', 'mean_GY(y)', 'mean_GY(z)','sd_LA(x)', 'sd_LA(y)', 'sd_LA(z)', 'sd_GY(x)', 'sd_GY(y)', 'sd_GY(z)'])
directory = os.path.join(os.getcwd(), 'hand\\testing')
x=1
firstTime = True
for filename in os.listdir(directory):
    if (filename.endswith(".csv")):
        filepath = os.path.join(directory, filename)
        testOriginal = pd.read_csv(filepath)
        test=testOriginal.copy()
        
#         num_rows = test.shape[0]
#         start_row = 0
#         end_row = num_rows/2
#         end_row = math.ceil(end_row)
        num_rows_before = test.shape[0]
    
        fivePercent = num_rows_before * 0.2
        fivePercent = math.ceil(fivePercent)
        
        #test = test.iloc[fivePercent:]
        
        
        test = test.iloc[:-fivePercent]
        
        num_rows = test.shape[0]
        
    
        end_row_init = num_rows/2
        end_row_init = math.ceil(end_row_init)
        
        start_row = end_row_init
        end_row=num_rows+1
        
        
        print(fivePercent)   
        # Create a new row of data
        new_row = [filename,test['LA(x)'][start_row:end_row].mean(),test['LA(y)'][start_row:end_row].mean(),test['LA(z)'][start_row:end_row].mean(),test['GY(x)'][start_row:end_row].mean(),test['GY(y)'][start_row:end_row].mean(),test['GY(z)'][start_row:end_row].mean(),test['LA(x)'][start_row:end_row].std(),test['LA(y)'][start_row:end_row].std(),test['LA(z)'][start_row:end_row].std(),test['GY(x)'][start_row:end_row].std(),test['GY(y)'][start_row:end_row].std(),test['GY(z)'][start_row:end_row].std()]

        # Add the new row to the DataFrame
        df_testingHalf.loc[len(df_testingHalf)] = new_row

3007
2902
2841
2659
2293
2407
2940

In [10]:
df_testingHalf

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,ola.csv,0.101133,-0.568853,0.981838,-0.010862,-0.033242,-0.021373,1.906360,2.689038,1.803614,1.746921,0.480926,0.721169
1,rolla.csv,0.234197,-0.614597,-0.092466,-0.005006,0.028111,0.029200,1.368909,1.486740,2.076941,0.529310,0.339050,1.239088
2,salwa.csv,0.144099,-1.020724,-0.145791,0.258313,-0.080329,0.654916,2.110948,1.680840,2.731512,1.040284,0.696270,1.159901
3,seifana.csv,-0.175207,-0.686154,0.390034,0.133595,0.254953,0.654673,1.493724,1.509737,2.546726,0.494243,0.532507,1.000572
4,tokhye.csv,0.191962,-0.633900,0.089395,-0.024434,0.044498,0.151637,2.061490,1.424009,3.104882,0.832848,0.620436,1.131680
5,youssef.csv,0.012217,-0.723384,1.113586,0.801431,-0.193601,0.045379,2.461315,2.412584,2.473354,1.494875,0.707911,0.720468
6,yusuf.csv,-0.128729,-0.418147,0.263753,0.004964,0.317315,0.577330,0.804180,0.708331,1.200859,0.233320,0.399851,0.680843

In [11]:
# label_column = 'name'
# label_encoder = LabelEncoder()
# df[label_column] = label_encoder.fit_transform(df[label_column])

In [12]:
df

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,0,0.900060,-0.965049,0.714376,-0.013971,-0.155567,0.041762,3.824209,2.992793,2.644413,1.009395,1.214170,1.437600
1,1,0.026040,-0.404830,0.129242,0.029543,0.155535,0.478177,0.841483,1.140295,1.569531,0.241602,0.400055,0.934533
2,2,0.392152,-0.462110,0.553301,-0.166631,0.020810,-0.001487,2.439593,2.094473,1.671452,1.035005,0.848799,1.010451
3,3,0.002777,-0.261593,0.043542,-0.367994,0.233681,-0.089440,1.610852,1.505165,0.867599,0.658520,0.445233,0.451626
4,4,-0.730693,-0.757379,0.506630,0.177046,-0.165480,0.604981,1.822200,2.397183,2.496371,1.028706,0.747703,1.236120
5,5,-0.006258,-0.526168,0.327254,0.105078,0.221316,0.469326,1.275037,1.564392,2.906907,0.373177,0.574268,0.965862
6,6,0.092198,-0.434006,0.262996,0.013348,0.089219,0.157710,1.059901,1.047598,1.543881,0.340469,0.529773,0.892956
7,7,0.330886,-0.183648,0.263214,0.021105,-0.067694,-0.170577,1.089285,0.966052,1.721033,0.400270,0.542752,0.824878
8,8,0.712194,-1.816702,0.990533,0.443608,-0.429236,-0.069807,4.284499,3.310251,2.383009,0.926856,0.977162,1.828933
9,9,0.269306,-0.448650,0.164584,-0.014954,-0.021956,-0.107034,1.060842,1.026368,1.688733,0.487122,0.455121,0.946564
10,10,0.168411,-0.370416,0.168652,0.028707,0.049733,0.155097,0.803503,0.913108,1.242390,0.235900,0.375851,0.912622
11,11,-0.673774,-0.951370,-0.417185,-0.478144,-0.128280,0.037818,2.549466,3.178923,1.639955,0.933311,0.490194,1.337298
12,12,0.053496,-0.261486,0.151948,0.054137,0.186128,0.340907,0.742779,0.821428,1.228647,0.267397,0.314201,0.482874
13,13,0.108910,-0.407179,0.662535,-0.020668,-0.032709,0.024278,1.683670,2.272056,1.581942,1.475667,0.399223,0.586404
14,14,0.216866,-0.528242,-0.049357,-0.001227,0.028715,-0.003257,1.217630,1.487113,1.943382,0.485284,0.321013,1.131530
15,15,0.211745,-0.727425,-0.076628,0.038244,-0.135960,0.468363,1.756172,1.651001,2.957945,0.954857,0.571199,1.080063
16,16,-0.150600,-0.546184,0.296190,0.104065,0.177521,0.474079,1.288246,1.284170,2.314333,0.465309,0.479223,0.928446
17,17,-0.039692,-0.316662,0.065548,0.089553,0.019198,0.403736,1.413875,1.223536,2.908938,0.579944,0.402881,0.858414
18,18,0.237372,-0.918822,1.106458,0.443280,-0.247797,0.058343,3.270762,3.094006,1.887799,1.316618,0.880323,1.120145
19,19,-0.062385,-0.446527,0.204720,0.011673,0.253974,0.461554,0.772383,0.671823,1.171294,0.192333,0.402633,0.646103

In [13]:
df_testingHalf

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,ola.csv,0.101133,-0.568853,0.981838,-0.010862,-0.033242,-0.021373,1.906360,2.689038,1.803614,1.746921,0.480926,0.721169
1,rolla.csv,0.234197,-0.614597,-0.092466,-0.005006,0.028111,0.029200,1.368909,1.486740,2.076941,0.529310,0.339050,1.239088
2,salwa.csv,0.144099,-1.020724,-0.145791,0.258313,-0.080329,0.654916,2.110948,1.680840,2.731512,1.040284,0.696270,1.159901
3,seifana.csv,-0.175207,-0.686154,0.390034,0.133595,0.254953,0.654673,1.493724,1.509737,2.546726,0.494243,0.532507,1.000572
4,tokhye.csv,0.191962,-0.633900,0.089395,-0.024434,0.044498,0.151637,2.061490,1.424009,3.104882,0.832848,0.620436,1.131680
5,youssef.csv,0.012217,-0.723384,1.113586,0.801431,-0.193601,0.045379,2.461315,2.412584,2.473354,1.494875,0.707911,0.720468
6,yusuf.csv,-0.128729,-0.418147,0.263753,0.004964,0.317315,0.577330,0.804180,0.708331,1.200859,0.233320,0.399851,0.680843

In [14]:
encodedNames = df.loc[13:, 'name'].values
print(encodedNames)

[13 14 15 16 17 18 19]

In [15]:
df_testingHalf['name'] = encodedNames
df_testingHalf

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,13,0.101133,-0.568853,0.981838,-0.010862,-0.033242,-0.021373,1.906360,2.689038,1.803614,1.746921,0.480926,0.721169
1,14,0.234197,-0.614597,-0.092466,-0.005006,0.028111,0.029200,1.368909,1.486740,2.076941,0.529310,0.339050,1.239088
2,15,0.144099,-1.020724,-0.145791,0.258313,-0.080329,0.654916,2.110948,1.680840,2.731512,1.040284,0.696270,1.159901
3,16,-0.175207,-0.686154,0.390034,0.133595,0.254953,0.654673,1.493724,1.509737,2.546726,0.494243,0.532507,1.000572
4,17,0.191962,-0.633900,0.089395,-0.024434,0.044498,0.151637,2.061490,1.424009,3.104882,0.832848,0.620436,1.131680
5,18,0.012217,-0.723384,1.113586,0.801431,-0.193601,0.045379,2.461315,2.412584,2.473354,1.494875,0.707911,0.720468
6,19,-0.128729,-0.418147,0.263753,0.004964,0.317315,0.577330,0.804180,0.708331,1.200859,0.233320,0.399851,0.680843

In [16]:
y_training_labels = df.pop('name')
y_training_labels

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
Name: name, dtype: int32

In [17]:
X_training_dataset = df.copy()

In [18]:
X_testing_dataset = df_testingHalf.copy()

In [19]:
y_testing_labels = X_testing_dataset.pop('name')

In [20]:
X_training_dataset.shape

(20, 12)

In [21]:
y_training_labels.shape

(20,)

In [22]:
X_testing_dataset.shape

(7, 12)

In [23]:
y_testing_labels.shape

(7,)

In [24]:
classifier = svm.SVC(kernel='linear', gamma='auto', C=2)

classifier.fit(X_training_dataset,y_training_labels)

y_testing_predict = classifier.predict(X_testing_dataset)

In [25]:
from sklearn.metrics import classification_report
print(classification_report(y_testing_labels,y_testing_predict))

              precision    recall  f1-score   support

          13       1.00      1.00      1.00         1
          14       1.00      1.00      1.00         1
          15       0.50      1.00      0.67         1
          16       1.00      1.00      1.00         1
          17       0.00      0.00      0.00         1
          18       1.00      1.00      1.00         1
          19       1.00      1.00      1.00         1

    accuracy                           0.86         7
   macro avg       0.79      0.86      0.81         7
weighted avg       0.79      0.86      0.81         7

C:\Users\szizo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\szizo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\szizo\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [26]:
#Create a svm Classifier
model = svm.SVC(C = 2, # reg paramater
                kernel='linear', #kernel{‘linear’, ‘poly’, ‘rbf’, ‘sigmoid’, ‘precomputed’}, default=’rbf’
               ) # Linear Kernel

#Train the model using the training sets
model.fit(X_training_dataset, y_training_labels)

#Predict the response for test dataset
y_pred = model.predict(X_testing_dataset)

from sklearn import metrics
y_pred = model.predict(X_testing_dataset)
print("Accuracy:",metrics.accuracy_score(y_testing_labels, y_pred))

Accuracy: 0.8571428571428571

In [27]:
from sklearn import metrics
y_pred = model.predict(X_training_dataset)
print("Accuracy:",metrics.accuracy_score(y_training_labels, y_pred))

Accuracy: 1.0

In [28]:
from sklearn import metrics
y_pred = model.predict(X_testing_dataset)
print("Accuracy:",metrics.accuracy_score(y_testing_labels, y_pred))

Accuracy: 0.8571428571428571