In [1]:
import pandas as pd
import numpy as np
import os
import math
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score

In [2]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

In [3]:
# filepath = "merged_u1-50_w001_resampled.csv"
filepath = "D:/online dataset csv files preprocessing/MEAN_SD_FRAMED_RESAMPLED_merged_u1-50_w001_resampled_differentFrames9_2.csv"

df_original = pd.read_csv(filepath)

In [4]:
df_original

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,1.0,-0.393514,-0.231500,0.259489,-0.136301,0.808596,0.365505,1.607389,2.060070,1.568203,0.718605,1.529494,0.896005
1,1.0,-0.205181,-0.095354,0.648272,-0.071586,0.571196,0.191575,2.171280,3.287738,3.263532,1.188947,1.934990,1.023624
2,1.0,0.200687,0.144119,0.598333,0.199495,0.328963,0.085658,2.768780,3.864657,4.327969,1.356173,2.328443,1.102517
3,1.0,0.977162,0.184893,0.420916,0.122411,0.074673,-0.052158,3.646011,3.797331,5.745886,1.701895,2.413996,0.913987
4,1.0,0.909982,-0.020074,0.289224,0.142197,0.195004,-0.011897,4.750163,3.410333,6.188731,1.714321,2.334115,0.861539
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10137,50.0,-0.989119,-0.926201,1.691194,0.137947,0.080430,-0.058074,3.129826,4.017784,4.452476,1.645062,1.228332,0.779350
10138,50.0,-1.153985,-0.822312,1.754602,0.084342,0.007069,-0.122377,3.376924,4.376823,4.656196,1.696041,1.331929,0.824680
10139,50.0,-1.112609,-0.923574,1.790004,-0.037886,0.016173,-0.150160,3.509659,4.391247,4.704499,1.732431,1.365022,0.826021
10140,50.0,-0.981503,-0.953431,1.609741,-0.032794,-0.009065,-0.163652,3.525594,4.273273,4.589295,1.716987,1.358047,0.815734
10141,50.0,-0.724209,-0.905043,1.751427,-0.032222,0.015230,-0.142528,3.434122,4.055750,4.525051,1.732508,1.354905,0.821063

In [5]:
filtered_df_17 = df_original[df_original['name'] == 17].copy()
filtered_df_17

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
3442,17.0,-0.093407,0.411678,-0.304824,-0.016648,0.016325,-0.049061,1.711943,1.774261,1.628555,0.763388,0.847065,0.498127
3443,17.0,0.070076,0.346217,0.025414,-0.007534,0.044344,-0.096758,1.732290,1.810640,1.543117,0.764237,0.860197,0.478564
3444,17.0,0.026784,0.265064,0.005283,0.025688,-0.163633,-0.031920,1.765569,1.822704,1.479054,0.778196,0.748703,0.447058
3445,17.0,-0.064204,0.291965,0.034143,-0.047558,-0.098845,-0.024993,1.724416,1.956246,1.578616,0.760110,0.775709,0.468235
3446,17.0,0.013233,0.335707,0.018976,-0.002984,-0.023933,-0.068568,1.834470,2.126064,1.621798,0.808259,0.798243,0.520446
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584,17.0,0.049077,0.323942,0.111023,-0.071895,-0.043915,-0.020808,2.025751,2.931811,1.779353,0.857972,0.857914,0.625319
3585,17.0,0.223376,0.246270,0.058749,-0.066924,-0.035837,-0.056136,2.018524,2.904763,1.688597,0.856430,0.850513,0.590908
3586,17.0,0.257785,0.130051,0.013483,-0.033782,0.011993,-0.085704,1.995133,2.870276,1.569297,0.866645,0.858148,0.596963
3587,17.0,0.236698,0.229412,0.037781,0.017031,-0.035397,-0.084921,2.012288,2.768105,1.576682,0.893657,0.810513,0.600786
3588,17.0,-0.046435,0.315064,-0.056001,0.029431,-0.194483,-0.040160,2.015514,2.832037,1.699815,0.883124,0.799974,0.621714

In [6]:
filtered_df_17['name'] = filtered_df_17['name'] - 1
filtered_df_17

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
3442,16.0,-0.093407,0.411678,-0.304824,-0.016648,0.016325,-0.049061,1.711943,1.774261,1.628555,0.763388,0.847065,0.498127
3443,16.0,0.070076,0.346217,0.025414,-0.007534,0.044344,-0.096758,1.732290,1.810640,1.543117,0.764237,0.860197,0.478564
3444,16.0,0.026784,0.265064,0.005283,0.025688,-0.163633,-0.031920,1.765569,1.822704,1.479054,0.778196,0.748703,0.447058
3445,16.0,-0.064204,0.291965,0.034143,-0.047558,-0.098845,-0.024993,1.724416,1.956246,1.578616,0.760110,0.775709,0.468235
3446,16.0,0.013233,0.335707,0.018976,-0.002984,-0.023933,-0.068568,1.834470,2.126064,1.621798,0.808259,0.798243,0.520446
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3584,16.0,0.049077,0.323942,0.111023,-0.071895,-0.043915,-0.020808,2.025751,2.931811,1.779353,0.857972,0.857914,0.625319
3585,16.0,0.223376,0.246270,0.058749,-0.066924,-0.035837,-0.056136,2.018524,2.904763,1.688597,0.856430,0.850513,0.590908
3586,16.0,0.257785,0.130051,0.013483,-0.033782,0.011993,-0.085704,1.995133,2.870276,1.569297,0.866645,0.858148,0.596963
3587,16.0,0.236698,0.229412,0.037781,0.017031,-0.035397,-0.084921,2.012288,2.768105,1.576682,0.893657,0.810513,0.600786
3588,16.0,-0.046435,0.315064,-0.056001,0.029431,-0.194483,-0.040160,2.015514,2.832037,1.699815,0.883124,0.799974,0.621714

In [7]:
import random
filtered_df = pd.DataFrame()
df_original_copy = df_original.copy()
for i in range(0,1):
    my_array = np.array([15])
    filtered_df = pd.concat([filtered_df, df_original[df_original['name'] == my_array[i]]], ignore_index=True)
    df_original_copy = df_original_copy[df_original_copy['name'] != my_array[i]]
filtered_df

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,15.0,-0.549634,-5.088613,-6.266376,-0.032618,0.084202,-0.106947,3.678267,6.799805,5.724383,1.345299,0.948775,0.838329
1,15.0,-0.601636,-1.301400,-2.613514,0.068225,0.092200,-0.043458,3.480044,4.280016,5.200381,1.313067,0.926288,0.847679
2,15.0,-0.399759,-0.422325,-0.337781,0.117484,0.095247,-0.038594,3.460600,3.905869,4.380584,1.316938,0.980875,0.871029
3,15.0,-0.356662,-0.404562,0.267953,0.094160,0.033954,-0.086948,3.535261,4.072536,4.398427,1.320737,1.025963,0.889832
4,15.0,-0.401970,-0.576315,0.423394,0.011711,0.034737,-0.128122,3.661855,4.160244,4.471407,1.362728,1.054182,0.901221
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,15.0,0.167429,-1.190361,-0.362031,-0.010657,0.115750,-0.116823,4.092245,4.741354,5.474314,1.371619,1.029294,0.930888
83,15.0,-0.475711,-0.574920,0.668125,0.036605,0.094406,-0.100394,4.300148,4.941808,5.000282,1.418572,1.145911,0.933680
84,15.0,-0.423826,-0.463498,0.780605,0.095677,0.066348,-0.078743,4.234785,4.866552,4.934721,1.408442,1.198440,0.945260
85,15.0,-0.439714,-0.423108,0.866216,0.118718,0.025240,-0.090657,4.187681,4.869377,4.940755,1.396380,1.213596,0.962546
86,15.0,-0.467975,-0.230039,0.942298,0.168405,0.004578,-0.068821,3.969993,4.738255,4.758090,1.312312,1.181079,0.948671

In [8]:
df_original_copy[df_original_copy['name'] == 15]

Empty DataFrame
Columns: [name, mean_LA(x), mean_LA(y), mean_LA(z), mean_GY(x), mean_GY(y), mean_GY(z), sd_LA(x), sd_LA(y), sd_LA(z), sd_GY(x), sd_GY(y), sd_GY(z)]
Index: []

In [9]:
filtered_df['name'] = filtered_df['name'] -1
filtered_df

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,14.0,-0.549634,-5.088613,-6.266376,-0.032618,0.084202,-0.106947,3.678267,6.799805,5.724383,1.345299,0.948775,0.838329
1,14.0,-0.601636,-1.301400,-2.613514,0.068225,0.092200,-0.043458,3.480044,4.280016,5.200381,1.313067,0.926288,0.847679
2,14.0,-0.399759,-0.422325,-0.337781,0.117484,0.095247,-0.038594,3.460600,3.905869,4.380584,1.316938,0.980875,0.871029
3,14.0,-0.356662,-0.404562,0.267953,0.094160,0.033954,-0.086948,3.535261,4.072536,4.398427,1.320737,1.025963,0.889832
4,14.0,-0.401970,-0.576315,0.423394,0.011711,0.034737,-0.128122,3.661855,4.160244,4.471407,1.362728,1.054182,0.901221
...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,14.0,0.167429,-1.190361,-0.362031,-0.010657,0.115750,-0.116823,4.092245,4.741354,5.474314,1.371619,1.029294,0.930888
83,14.0,-0.475711,-0.574920,0.668125,0.036605,0.094406,-0.100394,4.300148,4.941808,5.000282,1.418572,1.145911,0.933680
84,14.0,-0.423826,-0.463498,0.780605,0.095677,0.066348,-0.078743,4.234785,4.866552,4.934721,1.408442,1.198440,0.945260
85,14.0,-0.439714,-0.423108,0.866216,0.118718,0.025240,-0.090657,4.187681,4.869377,4.940755,1.396380,1.213596,0.962546
86,14.0,-0.467975,-0.230039,0.942298,0.168405,0.004578,-0.068821,3.969993,4.738255,4.758090,1.312312,1.181079,0.948671

In [10]:
X = df_original_copy.drop('name', axis=1).copy() # Features (all columns except the target)
y = df_original_copy['name'].copy()  # Labels

In [11]:
y = y -1

In [12]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0, stratify = y)

X_train, X_validation, y_train, y_validation = train_test_split(X_train_val, y_train_val, test_size = 0.1, random_state = 0, stratify = y_train_val)
X_train.shape, X_test.shape, X_validation.shape, y_train.shape, y_test.shape, y_validation.shape

((6334, 12), (3017, 12), (704, 12), (6334,), (3017,), (704,))

In [13]:
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test)
dval = xgb.DMatrix(X_validation, label=y_validation)

In [14]:
dtrain, dtest, dval

(<xgboost.core.DMatrix at 0x1d2daf257b0>,
 <xgboost.core.DMatrix at 0x1d2daf24ca0>,
 <xgboost.core.DMatrix at 0x1d2daf254e0>)

In [15]:
params = {
    'max_depth': 7,
    'learning_rate': 0.3,
    'objective': 'multi:softmax',
    'num_class': 50
}
epochs = 25
evals_result = {}  # Initialize an empty dictionary to store the evaluation results

In [16]:
# model = xgb.train(params, dtrain, epochs,  verbose_eval=1)

In [17]:
model = xgb.train(params, dtrain, epochs, evals=[(dtrain, 'train'), (dval, 'valid')],
                  evals_result=evals_result, verbose_eval=1)

[0]	train-mlogloss:0.69215	valid-mlogloss:0.79251
[1]	train-mlogloss:0.52615	valid-mlogloss:0.66149
[2]	train-mlogloss:0.41696	valid-mlogloss:0.57896
[3]	train-mlogloss:0.33950	valid-mlogloss:0.51836
[4]	train-mlogloss:0.28149	valid-mlogloss:0.47549
[5]	train-mlogloss:0.23748	valid-mlogloss:0.43973
[6]	train-mlogloss:0.20324	valid-mlogloss:0.41622
[7]	train-mlogloss:0.17605	valid-mlogloss:0.39568
[8]	train-mlogloss:0.15526	valid-mlogloss:0.37798
[9]	train-mlogloss:0.13848	valid-mlogloss:0.36722
[10]	train-mlogloss:0.12517	valid-mlogloss:0.35952
[11]	train-mlogloss:0.11480	valid-mlogloss:0.35181
[12]	train-mlogloss:0.10589	valid-mlogloss:0.34942
[13]	train-mlogloss:0.09876	valid-mlogloss:0.34531
[14]	train-mlogloss:0.09310	valid-mlogloss:0.34296
[15]	train-mlogloss:0.08832	valid-mlogloss:0.34171
[16]	train-mlogloss:0.08431	valid-mlogloss:0.34190
[17]	train-mlogloss:0.08086	valid-mlogloss:0.34473
[18]	train-mlogloss:0.07801	valid-mlogloss:0.34606
[19]	train-mlogloss:0.07570	valid-mlogloss:0.34786
[20]	train-mlogloss:0.07353	valid-mlogloss:0.35030
[21]	train-mlogloss:0.07180	valid-mlogloss:0.35294
[22]	train-mlogloss:0.07034	valid-mlogloss:0.35538
[23]	train-mlogloss:0.06890	valid-mlogloss:0.35727
[24]	train-mlogloss:0.06762	valid-mlogloss:0.35985

In [18]:
predictions = model.predict(dtest)

In [19]:
print(predictions)

[28. 28. 38. ...  9. 28. 47.]

In [20]:
accuracy_score(y_test, predictions)

0.8700696055684455

In [21]:
predictions_proba = model.predict(dtest, output_margin=True)
predictions_proba.shape

(3017, 50)

In [59]:
X_17 =filtered_df_17.drop('name', axis = 1).copy()
y_17 = filtered_df_17['name'].copy()
X_train_val_17, X_test_17, y_train_val_17, y_test_17 = train_test_split(X_17, y_17, test_size = 0.3, random_state = 0)
dtest_17 = xgb.DMatrix(X_test_17)
y_test_17.shape

(45,)

In [22]:
X_unk = filtered_df.drop('name', axis=1)
y_unk = filtered_df['name']

In [23]:
X_train_val_unk, X_test_unk, y_train_val_unk, y_test_unk = train_test_split(X_unk, y_unk, test_size = 0.3, random_state = 0, stratify = y_unk)

In [24]:
dtest_unk = xgb.DMatrix(X_test_unk)

In [25]:
y_test_unk.shape

(27,)

In [26]:
predictions_unk = model.predict(dtest_unk)

In [27]:
# Find the unique values and their respective counts
unique_values, value_counts = np.unique(predictions_unk, return_counts=True)

# Create a dictionary to store the results
value_occurrences = dict(zip(unique_values, value_counts))

# Print the number of occurrences for each unique value
for value, count in value_occurrences.items():
    print(f"Value {value} occurs {count} time(s).")

Value 7.0 occurs 6 time(s).
Value 18.0 occurs 1 time(s).
Value 27.0 occurs 1 time(s).
Value 30.0 occurs 7 time(s).
Value 32.0 occurs 1 time(s).
Value 43.0 occurs 7 time(s).
Value 49.0 occurs 4 time(s).

In [61]:
predictions_17 = model.predict(dtest_17)
# Find the unique values and their respective counts
unique_values, value_counts = np.unique(predictions_17, return_counts=True)

# Create a dictionary to store the results
value_occurrences = dict(zip(unique_values, value_counts))

# Print the number of occurrences for each unique value
for value, count in value_occurrences.items():
    print(f"Value {value} occurs {count} time(s).")

Value 16.0 occurs 44 time(s).
Value 48.0 occurs 1 time(s).

In [28]:
len(np.unique(predictions_unk))

7

In [29]:
predictions_proba = model.predict(dtest_unk, output_margin=True)

In [30]:
predictions_proba.shape

(27, 50)

In [31]:
true_pred_prob = []
false_pred_prob = []
true_pred_sec_prob = []
false_pred_sec_prob = []
true_pred_diff_f_s = []
false_pred_diff_f_s = []
for i in range (0,predictions_proba.shape[0]):
    probs_i = np.exp(predictions_proba[i]) / np.sum(np.exp(predictions_proba[i]))
    pred_class = np.argmax(probs_i)
    true_class = y_test_unk.iloc[i]##manual
    pred = probs_i[pred_class]
    probs_i[probs_i == pred] = np.min(probs_i) - 1
    sec_pred = np.max(probs_i)
    if(pred_class == true_class):#true_pred
        true_pred_prob.append(pred)
        true_pred_sec_prob.append(sec_pred)
        true_pred_diff_f_s.append(pred-sec_pred)
    else:
        false_pred_prob.append(pred)
        false_pred_sec_prob.append(sec_pred)
        false_pred_diff_f_s.append(pred-sec_pred)

In [32]:
# max(true_pred_sec_prob),
max(false_pred_sec_prob)

0.29668626

In [33]:
thresh = 0.9

In [34]:
count_above = sum(x > thresh for x in false_pred_diff_f_s)
count_below = sum(x < thresh for x in false_pred_diff_f_s)
# count_below_08 = sum(x < 0.5 for x in true_pred_diff_f_s)
count_above, count_below

(0, 27)

In [35]:
i=0

In [36]:
predictions_proba[i]

array([-2.4226105 , -2.5895538 , -0.78973055, -2.3874552 , -2.6171474 ,
       -1.3852531 , -2.389265  , -0.57664967, -1.2367959 , -2.594604  ,
       -2.6250653 , -2.0620751 ,  0.6149175 , -2.3838944 , -2.6534774 ,
       -2.6039248 , -2.613406  , -2.4792771 , -1.8100741 , -2.5405934 ,
        0.21510255, -2.2394314 , -1.7184914 , -2.6366494 , -2.1127079 ,
       -1.7224216 , -2.6312983 ,  2.731659  , -2.5062282 , -2.5484815 ,
        4.6845007 , -2.3204103 , -2.4734848 , -2.5869527 , -2.508144  ,
       -2.2300713 , -2.5810232 , -2.2422957 , -2.774242  , -2.5116615 ,
       -2.1550329 , -2.3009188 , -1.0177469 ,  2.34252   , -1.3318707 ,
       -1.879069  , -2.6520343 , -2.6467307 , -2.693979  , -1.5709511 ],
      dtype=float32)

In [37]:
np.argmax(predictions_proba[i])

30

In [38]:
y_test.iloc[i]

28.0

In [39]:
probs = np.exp(predictions_proba[i]) / np.sum(np.exp(predictions_proba[i]))
print(probs)

[6.1990280e-04 5.2459125e-04 3.1730311e-03 6.4208324e-04 5.1031372e-04
 1.7492109e-03 6.4092217e-04 3.9265775e-03 2.0291600e-03 5.2194862e-04
 5.0628907e-04 8.8900072e-04 1.2927223e-02 6.4437365e-04 4.9210683e-04
 5.1710627e-04 5.1222666e-04 5.8575178e-04 1.1437860e-03 5.5091461e-04
 8.6669801e-03 7.4452150e-04 1.2534834e-03 5.0045812e-04 8.4510871e-04
 1.2485667e-03 5.0314324e-04 1.0734810e-01 5.7017594e-04 5.4658600e-04
 7.5666344e-01 6.8660761e-04 5.8915449e-04 5.2595750e-04 5.6908466e-04
 7.5152301e-04 5.2908546e-04 7.4239209e-04 4.3612599e-04 5.6708639e-04
 8.1008591e-04 7.0012180e-04 2.5260856e-03 7.2743386e-02 1.8451252e-03
 1.0675314e-03 4.9281749e-04 4.9543817e-04 4.7257388e-04 1.4527623e-03]

In [40]:
probs[7]

0.0039265775

In [41]:
np.argmax(probs)

30

In [42]:
formatted_values = ["{:.8f}".format(value) for value in probs]
formatted_values

['0.00061990',
 '0.00052459',
 '0.00317303',
 '0.00064208',
 '0.00051031',
 '0.00174921',
 '0.00064092',
 '0.00392658',
 '0.00202916',
 '0.00052195',
 '0.00050629',
 '0.00088900',
 '0.01292722',
 '0.00064437',
 '0.00049211',
 '0.00051711',
 '0.00051223',
 '0.00058575',
 '0.00114379',
 '0.00055091',
 '0.00866698',
 '0.00074452',
 '0.00125348',
 '0.00050046',
 '0.00084511',
 '0.00124857',
 '0.00050314',
 '0.10734810',
 '0.00057018',
 '0.00054659',
 '0.75666344',
 '0.00068661',
 '0.00058915',
 '0.00052596',
 '0.00056908',
 '0.00075152',
 '0.00052909',
 '0.00074239',
 '0.00043613',
 '0.00056709',
 '0.00081009',
 '0.00070012',
 '0.00252609',
 '0.07274339',
 '0.00184513',
 '0.00106753',
 '0.00049282',
 '0.00049544',
 '0.00047257',
 '0.00145276']

In [43]:
# xgb_model = xgb.XGBClassifier()

In [44]:
# param_grid = {
#     'max_depth': [3, 5, 7],
#     'learning_rate': [0.1,0.2, 0.3, 0.01, 0.001],
#     'n_estimators': [100, 200, 300],
#     'objective': ['multi:softmax'],
#     'num_class': [50] 
# }

In [45]:
# grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=5)
# grid_search.fit(X_train, y_train)  # X and y are your training data

In [46]:
# best_params = grid_search.best_params_
# best_model = grid_search.best_estimator_
# best_score = grid_search.best_score_

In [47]:
# best_params

In [48]:
# best_score

In [49]:
# y_pred = best_model.predict(X_test)

# # Evaluate the predictions
# accuracy = accuracy_score(y_test, y_pred)
# accuracy

In [50]:
# xgb_model2 = xgb.XGBClassifier()

In [51]:
# param_grid2 = {
#     'max_depth': [7, 9, 11],
#     'learning_rate': [ 0.3, 0.4, 0.5],
#     'n_estimators': [ 300, 400, 500],
#     'objective': ['multi:softmax'],
#     'num_class': [50] 
# }

In [52]:
# grid_search2 = GridSearchCV(estimator=xgb_model2, param_grid=param_grid2, cv=5)
# grid_search2.fit(X_train, y_train)  # X and y are your training data

In [53]:
# best_params2 = grid_search2.best_params_
# best_model2 = grid_search2.best_estimator_
# best_score2 = grid_search2.best_score_

In [54]:
# best_params2

In [55]:
# best_score2

In [56]:
# y_pred2 = best_model2.predict(X_test)

# # Evaluate the predictions
# accuracy2 = accuracy_score(y_test, y_pred2)
# accuracy2