In [1]:
import pandas as pd
import numpy as np
import os
import math
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [2]:
import xgboost as xgb
from sklearn.model_selection import GridSearchCV

In [3]:
# filepath = "merged_u1-50_w001_resampled.csv"
filepath = "D:/online dataset csv files preprocessing/merged_u1-50_w001_resampled.csv"

df_original = pd.read_csv(filepath)

In [4]:
df_original

,timestamp,LAx,LAy,LAz,GYx,GYy,GYz,name
0,924313410000000,1.242813,-0.160181,-0.900440,0.194931,-0.004242,0.163818,1
1,924313420000000,1.117246,-0.187921,-1.529893,0.236458,0.076378,0.133293,1
2,924313430000000,0.912846,-0.192566,-1.570929,0.226074,0.012253,0.108246,1
3,924313440000000,0.874858,-0.227208,-1.453511,0.139336,-0.050667,0.085030,1
4,924313450000000,0.834022,-0.282976,-1.292671,-0.013374,-0.109314,0.078308,1
...,...,...,...,...,...,...,...,...
2055043,1368327120000000,-9.502644,-7.178468,4.246279,-2.834417,-0.120428,-0.987857,50
2055044,1368327130000000,-9.443804,-7.698220,3.059675,-2.638940,0.561997,-0.947715,50
2055045,1368327140000000,-8.345459,-6.805815,1.853457,-2.483606,1.225222,-0.954696,50
2055046,1368327150000000,-7.580540,-5.629017,1.559257,-2.429500,1.769765,-1.003565,50
2055047,1368327160000000,-6.952915,-4.589512,1.755390,-2.426010,2.099633,-0.980876,50

In [5]:
df_Xtime = df_original.copy()
df_Xtime = df_Xtime.drop(['timestamp'], axis = 1).copy()
df_Xtime.shape

(2055048, 7)

In [6]:
X = df_Xtime[['LAx', 'LAy', 'LAz','GYx', 'GYy', 'GYz']].copy()
y = df_Xtime['name'].copy()

In [7]:
scaler = StandardScaler()
X_transformed = X.copy()
X_transformed = scaler.fit_transform(X_transformed)

scaled_X = pd.DataFrame(data = X_transformed, columns = ['LAx', 'LAy', 'LAz','GYx', 'GYy', 'GYz'])
scaled_X['label'] = y.values

scaled_X

              LAx       LAy       LAz       GYx       GYy       GYz  label
0        0.359745 -0.067021 -0.237446  0.105221  0.035341  0.175545      1
1        0.322625 -0.073783 -0.418039  0.133911  0.092852  0.143484      1
2        0.262201 -0.074915 -0.429812  0.126737  0.047108  0.117177      1
3        0.250972 -0.083358 -0.396125  0.066811  0.002223  0.092793      1
4        0.238900 -0.096951 -0.349979 -0.038693 -0.039614  0.085733      1
...           ...       ...       ...       ...       ...       ...    ...
2055043 -2.816791 -1.777656  1.239172 -1.987696 -0.047543 -1.034070     50
2055044 -2.799397 -1.904341  0.898730 -1.852644  0.439278 -0.991908     50
2055045 -2.474708 -1.686826  0.552660 -1.745327  0.912402 -0.999240     50
2055046 -2.248585 -1.399994  0.468253 -1.707947  1.300863 -1.050568     50
2055047 -2.063049 -1.146625  0.524524 -1.705535  1.536180 -1.026737     50

[2055048 rows x 7 columns]

In [8]:
import scipy.stats as stats

Fs = 100
frame_size = Fs*6
hop_size = Fs*6

In [9]:
num_columns = frame_size*6
new_df = pd.DataFrame(columns=range(num_columns))
for i in range(0,num_columns):
    if i in range(0,frame_size):
        string = f"LAx_{i+1}"
        new_df = new_df.rename(columns={i: string})
        
    if i in range(frame_size,frame_size*2):
        string = f"LAy_{i+1}"
        new_df = new_df.rename(columns={i: string}) 
       
    if i in range(frame_size*2,frame_size*3):
        string = f"LAz_{i+1}"
        new_df = new_df.rename(columns={i: string}) 
       
    if i in range(frame_size*3,frame_size*4):
        string = f"GYx_{i+1}"
        new_df = new_df.rename(columns={i: string})
        
    if i in range(frame_size*4,frame_size*5):
        string = f"GYy_{i+1}"
        new_df = new_df.rename(columns={i: string}) 
       
    if i in range(frame_size*5,frame_size*6):
        string = f"GYz_{i+1}"
        new_df = new_df.rename(columns={i: string})

In [10]:
new_df

Empty DataFrame
Columns: [LAx_1, LAx_2, LAx_3, LAx_4, LAx_5, LAx_6, LAx_7, LAx_8, LAx_9, LAx_10, LAx_11, LAx_12, LAx_13, LAx_14, LAx_15, LAx_16, LAx_17, LAx_18, LAx_19, LAx_20, LAx_21, LAx_22, LAx_23, LAx_24, LAx_25, LAx_26, LAx_27, LAx_28, LAx_29, LAx_30, LAx_31, LAx_32, LAx_33, LAx_34, LAx_35, LAx_36, LAx_37, LAx_38, LAx_39, LAx_40, LAx_41, LAx_42, LAx_43, LAx_44, LAx_45, LAx_46, LAx_47, LAx_48, LAx_49, LAx_50, LAx_51, LAx_52, LAx_53, LAx_54, LAx_55, LAx_56, LAx_57, LAx_58, LAx_59, LAx_60, LAx_61, LAx_62, LAx_63, LAx_64, LAx_65, LAx_66, LAx_67, LAx_68, LAx_69, LAx_70, LAx_71, LAx_72, LAx_73, LAx_74, LAx_75, LAx_76, LAx_77, LAx_78, LAx_79, LAx_80, LAx_81, LAx_82, LAx_83, LAx_84, LAx_85, LAx_86, LAx_87, LAx_88, LAx_89, LAx_90, LAx_91, LAx_92, LAx_93, LAx_94, LAx_95, LAx_96, LAx_97, LAx_98, LAx_99, LAx_100, ...]
Index: []

[0 rows x 3600 columns]

In [11]:
label = []
def get_frames(scaled_X, frame_size, hop_size):
    df = scaled_X.copy()
    
    last_value = df['label'].iloc[-1]
    
    for j in range (1,last_value+1):
        filtered_df = df[df['label'] == j]
        filtered_df = filtered_df.drop('label', axis = 1)
        for i in range(0, len(filtered_df) - frame_size, hop_size):
            
            LAx = filtered_df['LAx'].values[i: i + frame_size]
            LAy = filtered_df['LAy'].values[i: i + frame_size]
            LAz = filtered_df['LAz'].values[i: i + frame_size]
            GYx = filtered_df['GYx'].values[i: i + frame_size]
            GYy = filtered_df['GYy'].values[i: i + frame_size]
            GYz = filtered_df['GYz'].values[i: i + frame_size]
            
            if(len(LAx) != frame_size):
                x=x+1
                continue
            
            label.append(j)
           
            merged_array = np.concatenate((LAx, LAy, LAz, GYx, GYy , GYz))
            new_df.loc[len(new_df)] = merged_array

In [12]:
get_frames(scaled_X,frame_size, hop_size)

In [13]:
new_df

,LAx_1,LAx_2,LAx_3,LAx_4,LAx_5,LAx_6,LAx_7,LAx_8,LAx_9,LAx_10,...,GYz_3591,GYz_3592,GYz_3593,GYz_3594,GYz_3595,GYz_3596,GYz_3597,GYz_3598,GYz_3599,GYz_3600
0,0.359745,0.322625,0.262201,0.250972,0.238900,0.222485,0.207377,0.191340,0.185856,0.181450,...,0.190963,0.170433,0.169784,0.172981,0.184536,0.213424,0.211492,0.195442,0.187116,0.184552
1,-0.169076,-0.164402,-0.151805,-0.272731,-0.597051,-0.593171,-0.444264,-0.133798,-0.009714,0.037284,...,-3.214607,-3.050352,-2.999036,-2.896376,-2.544133,-2.087957,-1.534267,-1.072962,-0.485262,-0.032286
2,-0.468491,-0.918428,-1.288186,-1.491514,-1.580992,-1.577450,-1.391323,-0.687764,-0.009369,0.314390,...,-0.518624,0.289765,0.622755,0.531003,0.275646,0.232655,0.232655,0.221116,0.100493,-0.109285
3,-0.906264,-0.851605,-1.480069,-2.276682,-2.516450,-2.499141,-2.067582,-0.596040,1.451763,2.654458,...,0.470688,0.411663,0.373167,0.303236,0.245709,0.189664,0.129365,0.049818,-0.127258,-0.269685
4,1.141035,1.147524,1.072081,1.022071,1.012888,0.822205,0.795602,1.025694,1.808360,2.291642,...,-0.077857,-0.058609,-0.013695,0.043391,0.178774,0.404611,0.637507,0.779950,0.730533,0.421294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3386,-0.686019,-0.567160,-0.303350,-0.088823,0.114107,0.148895,0.038733,-0.085924,-0.109117,0.015541,...,-1.417195,-1.166055,-0.949745,-0.760932,-0.577619,-0.419969,-0.269652,-0.154164,-0.024012,0.140970
3387,-1.048396,-0.859960,-0.419311,0.093814,0.856254,1.380974,2.097030,2.282566,0.937426,0.056127,...,0.320618,0.054813,-0.101003,-0.341144,-0.627113,-0.786596,-0.856255,-0.898418,-0.927748,-0.878253
3388,0.156143,-0.001853,-1.033900,-1.610803,-2.213797,-2.547183,-2.350051,-1.952886,-1.564419,-1.161457,...,-1.441026,-1.136725,-0.803094,-0.386973,0.076811,0.538761,0.984213,1.261016,0.956716,0.432439
3389,0.598242,0.314139,0.079319,0.085117,0.038733,-0.164198,-0.097520,0.128602,0.288048,0.256159,...,0.727574,0.694577,0.562592,0.313285,0.069478,-0.062508,-0.123001,-0.391556,-0.520333,-0.649111
3390,-0.080126,-0.378724,-0.546867,-0.575857,-0.596150,-0.832419,-1.051295,-1.619500,-2.187706,-2.547183,...,-0.238489,0.300453,0.894389,1.330676,1.338008,0.931052,0.656082,0.531428,0.613919,0.575424