In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split
import seaborn as sns # for plotting.
import os
import math

In [2]:
filepath = "D:/online dataset csv files preprocessing/merged_u1-50_w001_resampled.csv"
df_original = pd.read_csv(filepath)

In [3]:
df_original

,timestamp,LAx,LAy,LAz,GYx,GYy,GYz,name
0,924313410000000,1.242813,-0.160181,-0.900440,0.194931,-0.004242,0.163818,1
1,924313420000000,1.117246,-0.187921,-1.529893,0.236458,0.076378,0.133293,1
2,924313430000000,0.912846,-0.192566,-1.570929,0.226074,0.012253,0.108246,1
3,924313440000000,0.874858,-0.227208,-1.453511,0.139336,-0.050667,0.085030,1
4,924313450000000,0.834022,-0.282976,-1.292671,-0.013374,-0.109314,0.078308,1
...,...,...,...,...,...,...,...,...
2055043,1368327120000000,-9.502644,-7.178468,4.246279,-2.834417,-0.120428,-0.987857,50
2055044,1368327130000000,-9.443804,-7.698220,3.059675,-2.638940,0.561997,-0.947715,50
2055045,1368327140000000,-8.345459,-6.805815,1.853457,-2.483606,1.225222,-0.954696,50
2055046,1368327150000000,-7.580540,-5.629017,1.559257,-2.429500,1.769765,-1.003565,50
2055047,1368327160000000,-6.952915,-4.589512,1.755390,-2.426010,2.099633,-0.980876,50

In [4]:
import scipy.stats as stats

Fs = 100
frame_size = Fs*6 
hop_size =int( Fs*2)

In [5]:
df_framed = pd.DataFrame(columns=['name','mean_LA(x)', 'mean_LA(y)', 'mean_LA(z)', 'mean_GY(x)', 'mean_GY(y)', 'mean_GY(z)','sd_LA(x)', 'sd_LA(y)', 'sd_LA(z)', 'sd_GY(x)', 'sd_GY(y)', 'sd_GY(z)'])
def get_frames(df, frame_size, hop_size):
    
    last_value = df['name'].iloc[-1]
    for j in range (1,last_value+1): 
        filtered_df = df[df['name'] == j]
        filtered_df = filtered_df.drop('name', axis = 1)
        for i in range(0, len(filtered_df) - frame_size, hop_size):
            frame = filtered_df[i: i + frame_size]
            
            new_row = [j
                       ,frame['LAx'].mean(),frame['LAy'].mean(),frame['LAz'].mean()
                       ,frame['GYx'].mean(),frame['GYy'].mean(),frame['GYz'].mean()
                       ,frame['LAx'].std(),frame['LAy'].std(),frame['LAz'].std() 
                       ,frame['GYx'].std(),frame['GYy'].std(),frame['GYz'].std()]


            
            df_framed.loc[len(df_framed)] = new_row
            

    return df_framed

In [6]:
df_framed = get_frames(df_original,frame_size,hop_size)
df_framed

,name,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
0,1.0,-0.393514,-0.231500,0.259489,-0.136301,0.808596,0.365505,1.607389,2.060070,1.568203,0.718605,1.529494,0.896005
1,1.0,-0.205181,-0.095354,0.648272,-0.071586,0.571196,0.191575,2.171280,3.287738,3.263532,1.188947,1.934990,1.023624
2,1.0,0.200687,0.144119,0.598333,0.199495,0.328963,0.085658,2.768780,3.864657,4.327969,1.356173,2.328443,1.102517
3,1.0,0.977162,0.184893,0.420916,0.122411,0.074673,-0.052158,3.646011,3.797331,5.745886,1.701895,2.413996,0.913987
4,1.0,0.909982,-0.020074,0.289224,0.142197,0.195004,-0.011897,4.750163,3.410333,6.188731,1.714321,2.334115,0.861539
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10137,50.0,-0.989119,-0.926201,1.691194,0.137947,0.080430,-0.058074,3.129826,4.017784,4.452476,1.645062,1.228332,0.779350
10138,50.0,-1.153985,-0.822312,1.754602,0.084342,0.007069,-0.122377,3.376924,4.376823,4.656196,1.696041,1.331929,0.824680
10139,50.0,-1.112609,-0.923574,1.790004,-0.037886,0.016173,-0.150160,3.509659,4.391247,4.704499,1.732431,1.365022,0.826021
10140,50.0,-0.981503,-0.953431,1.609741,-0.032794,-0.009065,-0.163652,3.525594,4.273273,4.589295,1.716987,1.358047,0.815734
10141,50.0,-0.724209,-0.905043,1.751427,-0.032222,0.015230,-0.142528,3.434122,4.055750,4.525051,1.732508,1.354905,0.821063

In [7]:
occurrences = df_framed['name'].value_counts()
print(occurrences.mean())

202.84

In [8]:
X = df_framed.drop('name', axis=1)  # Features (all columns except the target)
y = df_framed['name']  # Labels

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0, stratify = y)

In [10]:
X_test

,mean_LA(x),mean_LA(y),mean_LA(z),mean_GY(x),mean_GY(y),mean_GY(z),sd_LA(x),sd_LA(y),sd_LA(z),sd_GY(x),sd_GY(y),sd_GY(z)
1737,-0.048555,-0.563331,-0.000072,-0.045317,0.252517,-0.092187,2.999954,4.124886,3.283342,1.581329,1.265775,0.778807
3668,0.535526,0.203991,-0.192242,0.139913,-0.120743,0.049629,2.480512,4.716539,2.931875,1.643100,1.255096,0.724381
8106,0.189763,0.406106,-0.247567,0.073980,-0.068745,0.089190,3.297929,4.872018,3.013259,1.414033,1.230386,1.197299
8127,0.300622,0.492426,0.063119,0.127368,-0.061640,-0.009582,3.337620,5.256239,2.839628,1.374139,1.107951,1.141733
10078,-1.626098,-1.086708,1.468791,0.001409,0.065664,-0.127769,3.629006,4.676408,4.920136,1.843410,1.475271,0.869412
...,...,...,...,...,...,...,...,...,...,...,...,...
4783,0.033860,0.082096,-0.188819,0.019454,-0.000631,0.036294,2.370309,3.669531,2.273574,1.349351,0.669353,0.717346
1428,0.133852,0.232867,-0.264341,0.114240,0.053151,0.033977,2.734921,4.260228,2.798640,1.138770,1.211825,1.028108
3838,0.319172,0.274180,-0.234409,-0.075965,0.016344,0.160497,2.852045,5.091124,3.089355,1.720847,1.323602,0.774527
3924,0.336162,0.159250,-0.286410,0.017188,-0.001673,0.125675,2.712141,4.743528,3.164273,1.661232,1.210894,0.741654
8490,-0.196862,-0.000919,0.398161,-0.104557,0.076968,-0.101110,2.435175,3.935465,2.876664,1.590111,1.417614,0.481974

In [11]:
occurrences = y_test.value_counts()
print(occurrences.mean())

60.86

In [12]:
X_train.shape, X_test.shape

((7099, 12), (3043, 12))

In [13]:
y_train.shape, y_test.shape

((7099,), (3043,))

In [14]:
#Create a svm Classifier
model = svm.SVC(C = 4, # reg paramater
                kernel='linear', #kernel{â€˜linearâ€™, â€˜polyâ€™, â€˜rbfâ€™, â€˜sigmoidâ€™, â€˜precomputedâ€™}, default=â€™rbfâ€™
               ) # Linear Kernel

#Train the model using the training sets
model.fit(X_train, y_train)


from sklearn import metrics
y_pred = model.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9214590864278672

In [16]:
# df_framed.to_csv('MEAN_SD_FRAMED_RESAMPLED_merged_u1-50_w001_resampled_differentFrames9_2.csv', index = False)